apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredAnnotations
metadata:
  name: require-scan-annotation
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Service"]
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
      - apiGroups: ["argoproj.io"]
        kinds: ["Rollout"]
  parameters:
    exemptedServiceAccounts:
      - system:serviceaccount:openshift-gitops-operator:openshift-gitops-operator-controller-manager
      # - system:serviceaccount:openshift-monitoring:prometheus-k8s
    annotations:
      - key: "sonarqube-scan"
        allowedRegex: "^success$"