apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredAnnotations
metadata:
  name: all-must-have-certain-set-of-annotations
spec:
  match:
    kinds:
      # Workload resources
      - apiGroups: ["apps"]
        kinds: ["Deployment"] #"StatefulSet", "DaemonSet", "ReplicaSet"]
  parameters:
    message: "Deployments must have the 'sonarqube-status' annotation with value 'SONAR_STATUS=success'."
    annotations:
      - key: "sonarqube-status"
        allowedRegex: "^SONAR_STATUS=success$"  # Enforce exact match
